import esbuild from "esbuild";
import { chmodSync } from "node:fs";
import process from "node:process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const plugin = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  // 优先 SDK 的 ESM 入口：CJS barrel 是单文件（6MB+）无法 tree-shake，
  // ESM 入口可级联删除未引用代码，产物从 6.1MB 降到约 1MB。
  mainFields: ["module", "main"],
  // 不 minify：社区插件审核要求代码可审查（禁止混淆），minify 处于灰区，保守不压缩。
  minify: false,
  outfile: "main.js",
  platform: "node",
});

// CLI 产物：npx 直启的单文件 bundle（SDK/ws 全打入，零运行时依赖）。
// 与插件产物隔离（dist/），npm 包 files 只含 dist——插件资产仍走 GitHub release。
// format 用 cjs 而非 esm：SDK 的 axios 依赖链含 CJS require，原生 ESM 下
// esbuild 的 __require shim 会抛 Dynamic require（与 main.js 同款管线最稳）。
const cli = await esbuild.context({
  // shebang 必须是文件首行。
  banner: { js: `#!/usr/bin/env node\n${banner}` },
  entryPoints: ["src/cli.ts"],
  bundle: true,
  format: "cjs",
  platform: "node",
  target: "node18",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  mainFields: ["module", "main"],
  minify: false,
  outfile: "dist/cli.cjs",
});

if (prod) {
  await plugin.rebuild();
  await cli.rebuild();
  // npm bin 需要执行位（esbuild 产物默认 644）。
  chmodSync("dist/cli.cjs", 0o755);
  process.exit(0);
} else {
  await plugin.watch();
  await cli.watch();
}
